"""empty message

Revision ID: 59b500d7b3b3
Revises: 
Create Date: 2024-04-06 19:38:22.899277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59b500d7b3b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("pid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("people")
    # ### end Alembic commands ###
